### ISSUE TITLE
IllegalArgumentException when calling ReadApi.getExpand

### ISSUE THREAD

**Issue by Regniz** [ory/keto-client-java#6]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto-client-java/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto-client-java/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When calling the getExpand method with parameters from the [cat videos example](https://www.ory.sh/docs/keto/quickstart), an IllegalArgumentException (log output below) is thrown.

### Code
```java

@Component
public class StartupApplicationListenerExample implements ApplicationListener<ContextRefreshedEvent> {

    private static Logger logger = LoggerFactory.getLogger(StartupApplicationListenerExample.class);

    private final String ketoApiUrl;

    public StartupApplicationListenerExample(@Value("${keto.api.url}") String ketoApiUrl) {
        this.ketoApiUrl = ketoApiUrl;
    }

     @Override
     public void onApplicationEvent(ContextRefreshedEvent event) {

        // Make a call to Keto and expand a tree with all subjects that can view /cats/1.mp4
        ReadApi api = new ReadApi();
        api.setCustomBaseUrl(ketoApiUrl);

        String namespace = "videos";
        String _object = "/cats/1.mp4";
        String relation = "view";
        String subjectId = "*";
        String subjectSetNamespace = null;
        String subjectSetObject = null;
        String subjectSetRelation = null;
        Long maxDepth = null;
        try {

            ExpandTree responseExpand = api.getExpand(namespace, _object, relation, 3L);
            logger.info("Response Expand: {}", responseExpand);
        } catch (ApiException e) {
            logger.info("Response body: {}", e.getResponseBody());
            throw new IllegalStateException("Could not perform API request", e);
        }
    }
}
```

#### Relevant line
```java
ExpandTree responseExpand = api.getExpand(namespace, _object, relation, 3L);
```

### Reproducing the bug

1. Follow the cat video quickstart example here: https://www.ory.sh/docs/keto/quickstart
2. Call `ReadApi.getExpand("videos", "/cats/1.mp4", "view", 3L);`
3. `java.lang.IllegalArgumentException: Unexpected value 'union'`

### Relevant log output

```shell
java.lang.IllegalArgumentException: Unexpected value 'union'
	at sh.ory.keto.model.ExpandTree$TypeEnum.fromValue(ExpandTree.java:76) ~[keto-client-0.8.0-alpha.1.jar:na]
	at sh.ory.keto.model.ExpandTree$TypeEnum$Adapter.read(ExpandTree.java:88) ~[keto-client-0.8.0-alpha.1.jar:na]
	at sh.ory.keto.model.ExpandTree$TypeEnum$Adapter.read(ExpandTree.java:79) ~[keto-client-0.8.0-alpha.1.jar:na]
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199) ~[gson-2.8.9.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[gson-2.8.9.jar:na]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[gson-2.8.9.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar:na]
	at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar:na]
	at sh.ory.keto.JSON.deserialize(JSON.java:153) ~[keto-client-0.8.0-alpha.1.jar:na]
	at sh.ory.keto.ApiClient.deserialize(ApiClient.java:845) ~[keto-client-0.8.0-alpha.1.jar:na]
	at sh.ory.keto.ApiClient.handleResponse(ApiClient.java:1053) ~[keto-client-0.8.0-alpha.1.jar:na]
	at sh.ory.keto.ApiClient.execute(ApiClient.java:977) ~[keto-client-0.8.0-alpha.1.jar:na]
	at sh.ory.keto.api.ReadApi.getExpandWithHttpInfo(ReadApi.java:421) ~[keto-client-0.8.0-alpha.1.jar:na]
	at sh.ory.keto.api.ReadApi.getExpand(ReadApi.java:396) ~[keto-client-0.8.0-alpha.1.jar:na]
	at ab.xyz.ketopoc.ketopoc.StartupApplicationListenerExample.onApplicationEvent(StartupApplicationListenerExample.java:51) ~[classes/:na]
	at ab.xyz.ketopoc.ketopoc.StartupApplicationListenerExample.onApplicationEvent(StartupApplicationListenerExample.java:15) ~[classes/:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.4.jar:2.6.4]
	at ab.xyz.ketopoc.ketopoc.KetoPocApplication.main(KetoPocApplication.java:10) ~[classes/:na]
```

### Relevant configuration

```yml
keto.api.url="http://localhost:4466"
```

### Version

Java Client for Ory Keto 0.8.0-alpha.1 (https://search.maven.org/artifact/sh.ory.keto/keto-client/0.8.0-alpha.1/jar)

### On which operating system are you observing this issue?

Windows

### Additional Context

- ReadApi.getCheck does work from the same class. Everything is set up and running properly.
- When changing the max depth to 1L, the type of unexpected value changes from union to leaf.
- When setting max depth to 0L no exception is thrown. Instead the expected empty Expand Tree is returned.
- The IllegalArgumentException is thrown at ExpandTree.java > `public static TypeEnum fromValue(String value)` (line 70-77)
```java
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
```
- Debugging there:
![grafik](https://user-images.githubusercontent.com/82954818/156733685-b58ee315-050f-45ad-b189-b15753e467b6.png)

**Comment by zepatrik** [comment]
Problem was this: https://github.com/ory/keto/blob/v0.8.0-alpha.1/spec/swagger.json#L1306
Fixed already by https://github.com/ory/keto/commit/4c0eb4378175f284f73d8e0f9489942976019b2e but we need another release. Will trigger it now and close this once it succeeded.

**Comment by zepatrik** [comment]
Not sure how long it takes to land on maven, but the release succeeded. Can you confirm it works once updated?

**Comment by Regniz** [comment]
That was quick!

Yes, it is working now. With keto-client version `0.8.0-alpha.2` the response is the following tree.
```
Response Expand: class ExpandTree {
    children: [class ExpandTree {
        children: [class ExpandTree {
            children: null
            subjectId: null
            subjectSet: class SubjectSet {
                namespace: videos
                _object: /cats
                relation: owner
            }
            type: leaf
        }]
        subjectId: null
        subjectSet: class SubjectSet {
            namespace: videos
            _object: /cats/1.mp4
            relation: owner
        }
        type: union
    }, class ExpandTree {
        children: null
        subjectId: *
        subjectSet: null
        type: leaf
    }]
    subjectId: null
    subjectSet: class SubjectSet {
        namespace: videos
        _object: /cats/1.mp4
        relation: view
    }
    type: union
```

This corresponds to the response I get when using the keto command in PowerShell.
```
PS C:\...> keto expand view videos /cats/1.mp4 -d 3
∪ videos:/cats/1.mp4#view
├─ ∪ videos:/cats/1.mp4#owner
│  ├─ ☘ videos:/cats#owner️
├─ ☘ *️
```

Thank you for the quick fix!

**Comment by zepatrik** [comment]
Awesome, you are welcome :wink:
